#ARDMK_DIR=
#AVR_TOOLS_DIR – Directory where avr tools are installed

BOARD_TAG    = nano
BOARD_SUB    = atmega328
MONITOR_PORT = /dev/ttyUSB0
ARDUINO_DIR  = $(HOME)/Apps/Arduino/arduino-1.8.3
ARDUINO_SKETCHBOOK = $(HOME)/Arduino
include /usr/share/arduino/Arduino.mk

ARDUINO_LIBS = Adafruit_MAX31855 Soladin
